//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapeOpen.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapeOpen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon epa_seal_medium {
            get {
                object obj = ResourceManager.GetObject("epa_seal_medium", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CategorySpecifications&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Mass&lt;/Category&gt;
        ///    &lt;Aspen&gt;MASS&lt;/Aspen&gt;
        ///    &lt;SI_Unit&gt;kg&lt;/SI_Unit&gt;
        ///    &lt;Mass&gt;1&lt;/Mass&gt;
        ///    &lt;Time&gt;0&lt;/Time&gt;
        ///    &lt;Length&gt;0&lt;/Length&gt;
        ///    &lt;ElectricalCurrent&gt;0&lt;/ElectricalCurrent&gt;
        ///    &lt;Temperature&gt;0&lt;/Temperature&gt;
        ///    &lt;AmountOfSubstance&gt;0&lt;/AmountOfSubstance&gt;
        ///    &lt;Luminous&gt;0&lt;/Luminous&gt;
        ///    &lt;Currency&gt;0&lt;/Currency&gt;
        ///    &lt;Comment&gt;
        ///    &lt;/Comment&gt;
        ///  &lt;/Category_Spec&gt;
        ///  &lt;Category_Spec&gt;
        ///    &lt;Category&gt;Time&lt;/Category [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string unitCategories {
            get {
                return ResourceManager.GetString("unitCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Units&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;mol&lt;/Unit&gt;
        ///    &lt;Category&gt;AmountOfSubstance&lt;/Category&gt;
        ///    &lt;ConversionTimes&gt;1&lt;/ConversionTimes&gt;
        ///    &lt;ConversionPlus&gt;0&lt;/ConversionPlus&gt;
        ///    &lt;Comments&gt;0&lt;/Comments&gt;
        ///  &lt;/Unit_Specs&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;US$&lt;/Unit&gt;
        ///    &lt;Category&gt;Currency&lt;/Category&gt;
        ///    &lt;ConversionTimes&gt;1&lt;/ConversionTimes&gt;
        ///    &lt;ConversionPlus&gt;0&lt;/ConversionPlus&gt;
        ///    &lt;Comments&gt;0&lt;/Comments&gt;
        ///  &lt;/Unit_Specs&gt;
        ///  &lt;Unit_Specs&gt;
        ///    &lt;Unit&gt;A/cm2&lt;/Unit&gt;
        ///    &lt;Category&gt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string units {
            get {
                return ResourceManager.GetString("units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;dataroot xmlns:od=&quot;urn:schemas-microsoft-com:officedata&quot; generated=&quot;2008-09-23T14:52:13&quot;&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;THERMINOL 55&lt;/ChemicalName&gt;
        ///&lt;CAS&gt; 68855-24-3&lt;/CAS&gt;
        ///&lt;Rat_LD50_Value&gt;3500&lt;/Rat_LD50_Value&gt;
        ///&lt;Rat_LD50_Notes&gt;est&lt;/Rat_LD50_Notes&gt;
        ///&lt;Rat_LD50_Source&gt;C&lt;/Rat_LD50_Source&gt;
        ///&lt;OSHA_TWA_Notes&gt;N&lt;/OSHA_TWA_Notes&gt;
        ///&lt;FHM_LC50_Value&gt;171&lt;/FHM_LC50_Value&gt;
        ///&lt;FHM_LC50_Notes&gt;est - ave&lt;/FHM_LC50_Notes&gt;
        ///&lt;FHM_LC50_Source&gt;Q&lt;/FHM_LC50_Source&gt;
        ///&lt;/data&gt;
        ///&lt;data&gt;
        ///&lt;ChemicalName&gt;CAL [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WARdata {
            get {
                return ResourceManager.GetString("WARdata", resourceCulture);
            }
        }
    }
}
